ports:
  - port: 8100
    onOpen: open-preview
  - port: 9000-9999
    onOpen: ignore

tasks:
  - before: npm install -g @ionic/cli && npm install -g @angular/cli && npm install npm@latest -g && npm install @ionic/angular@latest &&npm install swiper@latest
    init: npm install
    command: ionic serve --host=localhost --port=8100 --disableHostCheck
